# .github/sync.yml
DRAMINGLING/Documents:
  - source: main.pdf      # 源文件路径（相对于当前仓库根目录）
    dest: Note for Algebraic Varieties.pdf   # 目标路径和文件名
    branch: main            # 目标分支（可选，默认为配置的default branch）
